package entity;
// Generated 01.10.2018 21:54:22 by Hibernate Tools 4.3.1



/**
 * DiplomVuz generated by hbm2java
 */
public class DiplomVuz  implements java.io.Serializable {


     private String image;
     private Man man;
     private String content;

    public DiplomVuz() {
    }

	
    public DiplomVuz(String image) {
        this.image = image;
    }
    public DiplomVuz(String image, Man man, String content) {
       this.image = image;
       this.man = man;
       this.content = content;
    }
   
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Man getMan() {
        return this.man;
    }
    
    public void setMan(Man man) {
        this.man = man;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


