package entity;
// Generated 01.10.2018 21:54:22 by Hibernate Tools 4.3.1


import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Man generated by hbm2java
 */
public class Man  implements java.io.Serializable {


     private int id;
     private SprFirm sprFirm;
     private String surname;
     private String name;
     private String otchestvo;
     private String birthDate;
     private Integer firmId;
     private Integer doljnostId;
     private Integer firm2Id;
     private Integer doljnost2Id;
     private String photo;
     private TrudBook trudBook;
     private Set udPoots = new HashSet(0);
     private Set diplomVuzs = new HashSet(0);
     private Passport passport;
     private SvidPovqual svidPovqual;
     private Boolean edit = false;

    public Man() {
    }

	
    public Man(int id) {
        this.id = id;
    }
    public Man(int id, SprFirm sprFirm, String surname, String name, String otchestvo, String birthDate, Integer firmId, Integer doljnostId, Integer firm2Id, Integer doljnost2Id, String photo, TrudBook trudBook, Set udPoots, Set diplomVuzs, Passport passport, SvidPovqual svidPovqual, Boolean edit) {
       this.id = id;
       this.sprFirm = sprFirm;
       this.surname = surname;
       this.name = name;
       this.otchestvo = otchestvo;
       this.birthDate = birthDate;
       this.firmId = firmId;
       this.doljnostId = doljnostId;
       this.firm2Id = firm2Id;
       this.doljnost2Id = doljnost2Id;
       this.photo = photo;
       this.trudBook = trudBook;
       this.udPoots = udPoots;
       this.diplomVuzs = diplomVuzs;
       this.passport = passport;
       this.svidPovqual = svidPovqual;
       this.edit = edit;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public SprFirm getSprFirm() {
        return this.sprFirm;
    }
    
    public void setSprFirm(SprFirm sprFirm) {
        this.sprFirm = sprFirm;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getOtchestvo() {
        return this.otchestvo;
    }
    
    public void setOtchestvo(String otchestvo) {
        this.otchestvo = otchestvo;
    }
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }
    public Integer getFirmId() {
        return firmId;
    }

    public void setFirmId(Integer firmId) {
        this.firmId = firmId;
    }
    public Integer getDoljnostId() {
        return this.doljnostId;
    }
    
    public void setDoljnostId(Integer doljnostId) {
        this.doljnostId = doljnostId;
    }
    public Integer getFirm2Id() {
        return this.firm2Id;
    }
    
    public void setFirm2Id(Integer firm2Id) {
        this.firm2Id = firm2Id;
    }
    public Integer getDoljnost2Id() {
        return this.doljnost2Id;
    }
    
    public void setDoljnost2Id(Integer doljnost2Id) {
        this.doljnost2Id = doljnost2Id;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public TrudBook getTrudBook() {
        return this.trudBook;
    }
    
    public void setTrudBook(TrudBook trudBook) {
        this.trudBook = trudBook;
    }
    public Set getUdPoots() {
        return this.udPoots;
    }
    
    public void setUdPoots(Set udPoots) {
        this.udPoots = udPoots;
    }
    public Set getDiplomVuzs() {
        return this.diplomVuzs;
    }
    
    public void setDiplomVuzs(Set diplomVuzs) {
        this.diplomVuzs = diplomVuzs;
    }
    public Passport getPassport() {
        return this.passport;
    }
    
    public void setPassport(Passport passport) {
        this.passport = passport;
    }
    public SvidPovqual getSvidPovqual() {
        return this.svidPovqual;
    }
    
    public void setSvidPovqual(SvidPovqual svidPovqual) {
        this.svidPovqual = svidPovqual;
    }
    
    public Boolean isEdit() {
        return edit;
    }

    public void setEdit(Boolean edit) {
        this.edit = edit;
    }
    
    /* public int getAge() { //Высчисляет возраст сотрудника через его ДР и возвращает на страницу man.jsp
    Date currentDate = new Date(); // Возвращает текущую дату
    Date birthDateForm = null;
         
         SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy"); //Класс SimpleDataFormat используется для того, чтобы отображать дату и время в удобном формате
         try {
       birthDateForm = format.parse(birthDate);
       } catch (Exception e) {
           e.printStackTrace();
       }
       long diffrent = currentDate.getTime() - birthDateForm.getTime(); // Количество миллисекунд между датами
       int age = (int) (diffrent/(24*3600*1000))/365; // Количество лет между датами
       return age;
    }       

    public int getAgeDays() { //Высчисляет количество дней, которое осталось до ДР сотрудника и возвращает на страницу man.jsp
        Date currentDate = new Date(); // Возвращает текущую дату
        Date birthDateForm = null;

        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy"); //Класс SimpleDataFormat используется для того, чтобы отображать дату и время в удобном формате
        try {
            birthDateForm = format.parse(birthDate);
        } catch (Exception e) {
            e.printStackTrace();
        }
        long diffrent = currentDate.getTime() - birthDateForm.getTime(); // Количество миллисекунд между датами
        int days = (int) ((365 - ((diffrent / (24 * 3600 * 1000)) % 365)) + ((diffrent / (24 * 3600 * 1000)) / (365 * 4))); // Количество дней до следующего дня рождения от текущей даты (учитывая весокосные годы)

        return days;
    }     */
    
    




}


