package entity;
// Generated 02.10.2018 21:28:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Man generated by hbm2java
 */
public class Man  implements java.io.Serializable {


     private int id;
     private SprDoljnost sprDoljnostByDoljnostId;
     private SprDoljnost sprDoljnostByDoljnost2Id;
     private SprFirm sprFirmByFirmId;
     private SprFirm sprFirmByFirm2Id;
     private String surname;
     private String name;
     private String otchestvo;
     private String birthDate;
     private String photo;
     private TrudBook trudBook;
     private Set udPoots = new HashSet(0);
     private Set diplomVuzs = new HashSet(0);
     private Passport passport;
     private SvidPovqual svidPovqual;
     private Boolean edit;

    public Man() {
    }

	
    public Man(int id) {
        this.id = id;
    }
    public Man(int id, SprDoljnost sprDoljnostByDoljnostId, SprDoljnost sprDoljnostByDoljnost2Id, SprFirm sprFirmByFirmId, SprFirm sprFirmByFirm2Id, String surname, String name, String otchestvo, String birthDate, String photo, TrudBook trudBook, Set udPoots, Set diplomVuzs, Passport passport, SvidPovqual svidPovqual, Boolean edit) {
       this.id = id;
       this.sprDoljnostByDoljnostId = sprDoljnostByDoljnostId;
       this.sprDoljnostByDoljnost2Id = sprDoljnostByDoljnost2Id;
       this.sprFirmByFirmId = sprFirmByFirmId;
       this.sprFirmByFirm2Id = sprFirmByFirm2Id;
       this.surname = surname;
       this.name = name;
       this.otchestvo = otchestvo;
       this.birthDate = birthDate;
       this.photo = photo;
       this.trudBook = trudBook;
       this.udPoots = udPoots;
       this.diplomVuzs = diplomVuzs;
       this.passport = passport;
       this.svidPovqual = svidPovqual;
       this.edit = edit;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public SprDoljnost getSprDoljnostByDoljnostId() {
        return this.sprDoljnostByDoljnostId;
    }
    
    public void setSprDoljnostByDoljnostId(SprDoljnost sprDoljnostByDoljnostId) {
        this.sprDoljnostByDoljnostId = sprDoljnostByDoljnostId;
    }
    public SprDoljnost getSprDoljnostByDoljnost2Id() {
        return this.sprDoljnostByDoljnost2Id;
    }
    
    public void setSprDoljnostByDoljnost2Id(SprDoljnost sprDoljnostByDoljnost2Id) {
        this.sprDoljnostByDoljnost2Id = sprDoljnostByDoljnost2Id;
    }
    public SprFirm getSprFirmByFirmId() {
        return this.sprFirmByFirmId;
    }
    
    public void setSprFirmByFirmId(SprFirm sprFirmByFirmId) {
        this.sprFirmByFirmId = sprFirmByFirmId;
    }
    public SprFirm getSprFirmByFirm2Id() {
        return this.sprFirmByFirm2Id;
    }
    
    public void setSprFirmByFirm2Id(SprFirm sprFirmByFirm2Id) {
        this.sprFirmByFirm2Id = sprFirmByFirm2Id;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getOtchestvo() {
        return this.otchestvo;
    }
    
    public void setOtchestvo(String otchestvo) {
        this.otchestvo = otchestvo;
    }
    public String getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(String birthDate) {
        this.birthDate = birthDate;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public TrudBook getTrudBook() {
        return this.trudBook;
    }
    
    public void setTrudBook(TrudBook trudBook) {
        this.trudBook = trudBook;
    }
    public Set getUdPoots() {
        return this.udPoots;
    }
    
    public void setUdPoots(Set udPoots) {
        this.udPoots = udPoots;
    }
    public Set getDiplomVuzs() {
        return this.diplomVuzs;
    }
    
    public void setDiplomVuzs(Set diplomVuzs) {
        this.diplomVuzs = diplomVuzs;
    }
    public Passport getPassport() {
        return this.passport;
    }
    
    public void setPassport(Passport passport) {
        this.passport = passport;
    }
    public SvidPovqual getSvidPovqual() {
        return this.svidPovqual;
    }
    
    public void setSvidPovqual(SvidPovqual svidPovqual) {
        this.svidPovqual = svidPovqual;
    }
    public Boolean getEdit() {
        return edit;
    }

    public void setEdit(Boolean edit) {
        this.edit = edit;
    }




}


