package entity;
// Generated 02.10.2018 21:28:39 by Hibernate Tools 4.3.1



/**
 * Passport generated by hbm2java
 */
public class Passport  implements java.io.Serializable {


     private int manId;
     private Man man;
     private String dateOkonch;
     private String image;
     private String content;

    public Passport() {
    }

	
    public Passport(Man man) {
        this.man = man;
    }
    public Passport(Man man, String dateOkonch, String image, String content) {
       this.man = man;
       this.dateOkonch = dateOkonch;
       this.image = image;
       this.content = content;
    }
   
    public int getManId() {
        return this.manId;
    }
    
    public void setManId(int manId) {
        this.manId = manId;
    }
    public Man getMan() {
        return this.man;
    }
    
    public void setMan(Man man) {
        this.man = man;
    }
    public String getDateOkonch() {
        return this.dateOkonch;
    }
    
    public void setDateOkonch(String dateOkonch) {
        this.dateOkonch = dateOkonch;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


