package entity;
// Generated 01.10.2018 21:54:22 by Hibernate Tools 4.3.1



/**
 * SprDoljnost generated by hbm2java
 */
public class SprDoljnost  implements java.io.Serializable {


     private int id;
     private String doljnost;

    public SprDoljnost() {
    }

    public SprDoljnost(int id, String doljnost) {
       this.id = id;
       this.doljnost = doljnost;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDoljnost() {
        return this.doljnost;
    }
    
    public void setDoljnost(String doljnost) {
        this.doljnost = doljnost;
    }




}


