package entity;
// Generated 01.10.2018 21:54:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * SprFirm generated by hbm2java
 */
public class SprFirm  implements java.io.Serializable {


     private int id;
     private String firm;
     private Set mans = new HashSet(0);

    public SprFirm() {
    }

	
    public SprFirm(int id) {
        this.id = id;
    }
    public SprFirm(int id, String firm, Set mans) {
       this.id = id;
       this.firm = firm;
       this.mans = mans;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirm() {
        return this.firm;
    }
    
    public void setFirm(String firm) {
        this.firm = firm;
    }
    public Set getMans() {
        return this.mans;
    }
    
    public void setMans(Set mans) {
        this.mans = mans;
    }




}


