package entity;
// Generated 01.10.2018 21:54:22 by Hibernate Tools 4.3.1



/**
 * SprSex generated by hbm2java
 */
public class SprSex  implements java.io.Serializable {


     private int id;
     private String sex;

    public SprSex() {
    }

	
    public SprSex(int id) {
        this.id = id;
    }
    public SprSex(int id, String sex) {
       this.id = id;
       this.sex = sex;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }




}


