package entity;
// Generated 04.10.2018 19:07:38 by Hibernate Tools 4.3.1



/**
 * TrudBook generated by hbm2java
 */
public class TrudBook  implements java.io.Serializable {


     private String image;
     private Integer manId;
     private String content;

    public TrudBook() {
    }

	
    public TrudBook(String image) {
        this.image = image;
    }
    public TrudBook(String image, Integer manId, String content) {
       this.image = image;
       this.manId = manId;
       this.content = content;
    }
   
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Integer getManId() {
        return this.manId;
    }
    
    public void setManId(Integer manId) {
        this.manId = manId;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


