package entity;
// Generated 02.10.2018 21:28:39 by Hibernate Tools 4.3.1



/**
 * UdPoot generated by hbm2java
 */
public class UdPoot  implements java.io.Serializable {


     private String image;
     private Man man;
     private String dateOkonch;
     private String content;

    public UdPoot() {
    }

	
    public UdPoot(String image) {
        this.image = image;
    }
    public UdPoot(String image, Man man, String dateOkonch, String content) {
       this.image = image;
       this.man = man;
       this.dateOkonch = dateOkonch;
       this.content = content;
    }
   
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Man getMan() {
        return this.man;
    }
    
    public void setMan(Man man) {
        this.man = man;
    }
    public String getDateOkonch() {
        return this.dateOkonch;
    }
    
    public void setDateOkonch(String dateOkonch) {
        this.dateOkonch = dateOkonch;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


